// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDP3hh8g3O2poJbf3hnzK8lpdpZlFbRJ8g',
    appId: '1:188870210143:web:27156a8ac4ff10d54421ea',
    messagingSenderId: '188870210143',
    projectId: 'product-repo-d6e27',
    authDomain: 'product-repo-d6e27.firebaseapp.com',
    databaseURL: 'https://product-repo-d6e27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'product-repo-d6e27.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb7aoPrYpkXom58AwOpPPAWaIRvlPkR0A',
    appId: '1:188870210143:android:2e297a9d9d90f9ea4421ea',
    messagingSenderId: '188870210143',
    projectId: 'product-repo-d6e27',
    databaseURL: 'https://product-repo-d6e27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'product-repo-d6e27.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaiglA2tnfBSK1X7VfaMNxjFab-1Xb0UA',
    appId: '1:188870210143:ios:e71ffd06662160ac4421ea',
    messagingSenderId: '188870210143',
    projectId: 'product-repo-d6e27',
    databaseURL: 'https://product-repo-d6e27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'product-repo-d6e27.firebasestorage.app',
    iosBundleId: 'com.example.fireProvider',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDP3hh8g3O2poJbf3hnzK8lpdpZlFbRJ8g',
    appId: '1:188870210143:web:2c8d6d80ff5085184421ea',
    messagingSenderId: '188870210143',
    projectId: 'product-repo-d6e27',
    authDomain: 'product-repo-d6e27.firebaseapp.com',
    databaseURL: 'https://product-repo-d6e27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'product-repo-d6e27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaiglA2tnfBSK1X7VfaMNxjFab-1Xb0UA',
    appId: '1:188870210143:ios:e71ffd06662160ac4421ea',
    messagingSenderId: '188870210143',
    projectId: 'product-repo-d6e27',
    databaseURL: 'https://product-repo-d6e27-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'product-repo-d6e27.firebasestorage.app',
    iosBundleId: 'com.example.fireProvider',
  );

}